CHARACTERS = {
    8: {
        3: [
            'Euron Greyjoy',
            'Cersei Lannister',
            'Qyburn',
            'Melisandre',
            'Beric Dondarrion',
            'The Night King',
            'Jorah Mormont',
            'Grey Worm',
            'Theon Greyjoy',
            'Jaime Lannister',
            'Varys',
            'Yara Greyjoy',
            'Sandor "The Hound" Clegane',
            'Davos Seaworth',
            'Tormund Giantsbane',
            'Meera Reed',
            'Daenerys Targaryen',
            'Brienne of Tarth',
            'Bronn',
            'Jon Snow',
            'Bran Stark',
            'Missandei',
            'Tyrion Lannister',
            'Sansa Stark',
            'Arya Stark',
            'Gendry Baratheon',
            'Gilly',
            'Samwell Tarly',
            'Yohn Royce',
            'Gregor "The Mountain" Clegane',
            'Lyanna Mormont',
            'Maester Wolkan',
            'Podrick Payne',
            '"Dolorous Edd" Tollett',
            'Drogon (Dragon)',
            'Rhaegel (Dragon)',
            'Ghost',
            'Nymeria',
            'Little Sam',
        ]
    }
}
